_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 15ec2c1d-6c26-4094-928f-5eeb2fb66c7b
name: 'Lullabot CRP'
mail: admin@example.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
